@startuml modeloDominio

!theme plain
hide empty members
hide circle
skinparam linetype polyline
left to right direction

package "Gestión Institucional y Convocatorias" {
  class Universidad
  class Convocatoria
  class PerfilBuscado

  Universidad "1" *-- "*" Convocatoria : oferta
  Convocatoria "1" o-- "*" PerfilBuscado : requiere
}

package "Usuarios y Roles del Sistema" {
  abstract class Usuario
  class Candidato
  class AlumnoProfer
  class TechLeader
  class GestorProfer

  Usuario <|-- Candidato
  Usuario <|-- AlumnoProfer
  Usuario <|-- TechLeader
  Usuario <|-- GestorProfer
}

package "Admisión y Evaluación Técnica" {
  class PruebaTecnica
  class BancoReactivos
  class ReactivoTeorico
  class RespuestaTeorica
  class EjercicioPractico
  class RubricaEvaluacion
  class CriterioEvaluacion
  class EntregaPractica
  class CalificacionCriterio
  class TestRunner

  Convocatoria "1" *-- "*" Candidato : postula
  Candidato "1" *-- "1..*" PruebaTecnica : rinde
  PruebaTecnica "1" o-- "*" ReactivoTeorico : incluye
  PruebaTecnica "1" o-- "1..*" EjercicioPractico : asigna

  ReactivoTeorico "1" -- "*" RespuestaTeorica : genera
  PruebaTecnica "1" *-- "*" RespuestaTeorica : contiene

  EjercicioPractico "1" *-- "1" RubricaEvaluacion : define
  RubricaEvaluacion "1" *-- "1..*" CriterioEvaluacion : desglosa
  EjercicioPractico "1" -- "*" EntregaPractica : produce
  PruebaTecnica "1" *-- "*" EntregaPractica : recopila

  EntregaPractica "1" *-- "*" CalificacionCriterio : evalúa
  CriterioEvaluacion "1" -- "*" CalificacionCriterio : referencia

  BancoReactivos "1" *-- "*" ReactivoTeorico : almacena
  BancoReactivos "1" *-- "*" EjercicioPractico : cataloga

  EntregaPractica "1" ..> "1" TestRunner : ejecuta en sandbox
  TechLeader "1" ..> "*" CalificacionCriterio : califica manualmente
}

package "CTS Academy (Formación On-Site)" {
  class RutaAprendizaje
  class ModuloFormativo
  class RecursoFormativo
  class LaboratorioOnSite
  class EntregaLaboratorio
  class RevisionTechLeader
  class SeguimientoPeriodico

  PerfilBuscado "1" -- "0..1" RutaAprendizaje : orienta
  RutaAprendizaje "1" *-- "1..*" ModuloFormativo : compone
  ModuloFormativo "1" *-- "*" RecursoFormativo : provee
  ModuloFormativo "1" *-- "*" LaboratorioOnSite : programa

  AlumnoProfer "1" -- "1" RutaAprendizaje : cursa
  LaboratorioOnSite "1" -- "*" EntregaLaboratorio : genera
  AlumnoProfer "1" *-- "*" EntregaLaboratorio : entrega
  EntregaLaboratorio "1" *-- "0..*" RevisionTechLeader : recibe
  TechLeader "1" -- "*" RevisionTechLeader : emite

  AlumnoProfer "1" *-- "*" SeguimientoPeriodico : registra
  TechLeader "1" -- "*" SeguimientoPeriodico : supervisa
  TechLeader "1" -- "*" AlumnoProfer : tutoriza
}

@enduml
